# Generated by Django 4.2.30 on 2026-08-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo_url', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('Power Sponsor', 'Power Sponsor'), ('Innovation Sponsor', 'Innovation Sponsor'), ('Pioneer Sponsor', 'Pioneer Sponsor'), ('HackDay Sponsor', 'HackDay Sponsor'), ('AV Luminary Awards Sponsor', 'AV Luminary Awards Sponsor'), ('Community Sponsor', 'Community Sponsor')], default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
