# Generated by Django 4.2.30 on 2026-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image_url', models.URLField(max_length=500)),
                ('designation', models.CharField(help_text="e.g. 'Co-founder and Group CEO, Fractal'", max_length=255)),
                ('company_img_url', models.URLField(max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('heading', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('instructors', models.ManyToManyField(to='app.speaker')),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
