# Generated by Django 4.2.30 on 2026-08-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session_remove_speaker_tags_delete_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='app.speaker'),
        ),
    ]
