# Generated by Django 4.2.30 on 2026-08-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_session_speakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=250)),
                ('linkedin_url', models.URLField()),
                ('company_name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='workshop',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='app.speaker'),
        ),
    ]
