# Generated by Django 4.2.30 on 2026-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jury_alter_workshop_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
