# Generated by Django 4.2.30 on 2026-08-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_session_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
