# Generated by Django 4.2.30 on 2026-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_workshop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_sold_out',
            field=models.BooleanField(default=False, help_text="Toggle on once a workshop fills up to stamp it 'Sold Out' on the site."),
        ),
    ]
