# Generated by Django 4.2.30 on 2026-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_workshop_is_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
