# Generated by Django 4.2.30 on 2026-08-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_workshop_is_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, help_text="'About the Workshop' body. Rendered as raw HTML — paragraphs, <ul>/<li>, <strong>."),
        ),
        migrations.CreateModel(
            name='WorkshopModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, help_text='Module body shown in the accordion. Rendered as raw HTML.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.workshop')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
