# Generated by Django 4.2.30 on 2026-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_workshop_description_workshopmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshopmodule',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
