# Generated by Django 4.2.30 on 2026-08-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_workshop_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='app.speaker'),
        ),
    ]
