# Generated by Django 4.2.30 on 2026-08-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_session_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_moderator', to='app.speaker'),
        ),
    ]
