# Generated by Django 4.2.30 on 2026-08-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_session_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='romoderator', to='app.speaker'),
        ),
        migrations.DeleteModel(
            name='WorkshopModule',
        ),
    ]
