# Generated by Django 4.2.30 on 2026-08-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_downloaddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceTicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('companyName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloaddetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='ConferenceWorkshopTicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('companyName', models.CharField(blank=True, max_length=100, null=True)),
                ('workshops', models.ManyToManyField(blank=True, null=True, related_name='ticket', to='app.workshop')),
            ],
        ),
    ]
