# Generated by Django 4.2.30 on 2026-08-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_conferenceticketdetail_workshop_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jury',
        ),
    ]
