# Generated by Django 4.2.30 on 2026-08-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_jury'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
