# Generated by Django 4.2.30 on 2026-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_workshop_discount_alter_workshop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
