# Generated by Django 4.2.30 on 2026-08-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConferenceTicketDetail',
        ),
        migrations.DeleteModel(
            name='ConferenceWorkshopTicketDetail',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
