# Generated by Django 4.2.30 on 2026-08-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_conferenceticketdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='workshops',
            field=models.ManyToManyField(blank=True, to='app.workshop'),
        ),
    ]
